language: php
sudo: required
 
matrix:
    include:
        - os: linux
          dist: trusty          
services:
  - docker

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - uname -a
  - php --version
  - docker version
  - composer self-update
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
  - ip addr # for confirmation. can be skipped

install:
  - composer install
  - docker-compose -f docker-compose.yml -f docker-compose-all.yml up -d

script:
  - php vendor/bin/codecept --debug run acceptance
  - php vendor/bin/codecept run functional





