language: python
dist: trusty

python:
  - 2.7

services:
  - docker

before_install:
  - docker version

install:
  - docker-compose up

script:
  - docker ps | grep -q dev_web

after_success:
  - ./automate-docker-hub-build.sh




