language: php
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          php: 5.5
        - os: linux
          dist: trusty
          sudo: required
          php: 5.6
       
services:
  - docker

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - php --version
  - docker version
  - composer self-update

install:
  - composer install
  - docker-compose up -d

script:
  - php vendor/bin/codecept run functional




