language: python
dist: trusty
env:
  - SYMFONY_VERSION="dev-master" DB=mysql
python:
  - 2.7

services:
  - docker

before_install:
  - docker version

install:
  - docker build -t web-env .

before_script:
  - pip install mock
  - pip install requests
  - pip install feedparser

before_script: 
  - docker ps 
script:
  - docker ps | grep -q blog
  - python tests.py



