language: php
sudo: required
 
matrix:
    include:
        - os: linux
          dist: trusty          
services:
  - docker

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - uname -a
  - php --version
  - docker version
  - composer self-update

install:
  - composer install
  - docker-compose -f docker-compose.yml up -d

script:
  - php vendor/bin/codecept run functional




