language: php
sudo: required
env:
  matrix:
  - OS_TYPE=centos OS_VERSION=6
  - OS_TYPE=centos OS_VERSION=7
  
matrix:
    include:
        - os: linux
          dist: trusty          
          php: 5.5
        - os: linux
          dist: trusty
          sudo: required
          php: 5.6
        - os: osx
          osx_image: xcode7.2
          language: generic
          
services:
  - docker

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - php --version
  - docker version
  - composer self-update

install:
  - composer install
  - docker-compose up -d

script:
  - php vendor/bin/codecept run functional




