dist: trusty

language: php
php:
  - 5.5.9

services:
  - docker

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - docker version

install:
  - docker-compose up -d

before-script:
  - composer self-update
  - composer install

script:
  - docker ps | grep -q dev_web
  - php vendor/bin/codecept run acceptance




