dist: trusty

language: php
php: 5.5

services:
  - docker

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - docker version
  - curl -LsS http://codeception.com/codecept.phar -o /usr/local/bin/codecept
  - chmod a+x /usr/local/bin/codecept

install:
  - docker-compose up -d

script:
  - docker ps | grep -q dev_web
  - php vendor/bin/codecept run acceptance




