language: php
sudo: required

env:
  global:
    - REPO=orangehrm/orangehrm-environment-images
    - TAG=dev-5.6
    
  

jobs:
  include:
    - stage: test
      matrix:
        include:
          - os: linux
            dist: trusty  
      services:
        - docker
      env:
        - TEST_SUITE=unit
        - TEST_SUITE=functional
        - TEST_SUITE=acceptance
      cache:
        directories:
          - vendor
          - $HOME/.composer/cache
      before_install:
        - uname -a
        - php --version
        - docker version
        - composer self-update
        - docker build -t $REPO:$TAG docker-image
         
      install:
        - composer install
        - docker-compose up -d
      script: php vendor/bin/codecept run $TEST_SUITE
      
    - stage: push to dockerhub
      env: TEST_SUITE=none
      services:
        - docker
      before_install:
        - uname -a
        - php --version
        - docker version
        - composer self-update
        - docker build -t $REPO:$TAG docker-image
      install: skip
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push $REPO:$TAG     

