language: python
dist: trusty
env:
  - SYMFONY_VERSION="dev-master" DB=mysql
python:
  - 2.7

services:
  - docker

before_install:
  - docker version

install:
  - docker build -t rshariffdeen/web-dev-env .

before_script:
  - docker run -d --name="dev" rshariffdeen/web-dev-env

script:
  - docker ps | grep -q dev




