language: python
dist: trusty
env:
  - SYMFONY_VERSION="dev-master" DB=mysql
python:
  - 2.7

services:
  - docker

before_install:
  - docker version

install:
  - docker build -t rshariffdeen/web-dev-env .

before_script:
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y curl

script:
  - docker run -d --name="dev" rshariffdeen/web-dev-env
  - docker ps | grep -q dev

after_success:
  - ./automate-docker-hub-build.sh




