language: php
sudo: required

env:
  matrix:
  - TEST_SUITE=unit
  - TEST_SUITE=functional
  - TEST_SUITE=acceptance
  global:
  - REPO=orangehrm/orangehrm-environment-images
  - TAG=dev-7.1

matrix:
    include:
        - os: linux
          dist: trusty          
services:
  - docker

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - uname -a
  - php --version
  - docker version
  - composer self-update
  - docker build -t $REPO:$TAG docker-image

install:
  - composer install
  - docker-compose up -d

script:
  - php vendor/bin/codecept run $TEST_SUITE

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $REPO:$TAG




