dist: trusty
sudo: required

language: php
php: 5.5

services:
  - docker

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - docker version
  - composer self-update

install:
  - composer install
  - docker-compose up -d

script:
  - php vendor/bin/codecept run
  - docker ps
  - docker exec dev_web ping db -c 2




