version: '2.1'
services:
  ubuntuweb71:
    image: orangehrm/orangehrm-environment-images:dev-5.6-centos
    ports:
      - "9036:443"
    volumes:
      - ./html:/var/www/html
      - ./config/ubuntuweb71/php/php.ini:/etc/php.ini
      - ./config/ubuntuweb71/mysql-client:/etc/mysql
      - ./config/ubuntuweb71/apache2/sites-available:/etc/httpd/sites-available
      - ./config/ubuntuweb71/apache2/sites-enabled:/etc/httpd/sites-enabled
      - ./config/ubuntuweb71/apache2/cert:/etc/httpd/cert
      - ./config/ubuntuweb71/apache2/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
      - ./logs/apache_logs/web56:/var/log/httpd
      - /etc/localtime:/etc/localtime
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      ohrmdevnet-ubuntu:
        ipv4_address: 10.10.0.56
    restart: always
    container_name: dev_ubuntu_web_71

  ubuntuphpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "9082:80"
    environment:
      PMA_HOSTS: ubuntudb102
    networks:
      ohrmdevnet-ubuntu:
        ipv4_address: 10.10.0.20
    restart: always
    container_name: dev_ubuntu_phpmyadmin

  ubuntudb102:
    image: mariadb:10.2
    expose:
      - "3306"
    volumes:
      - ./config/db102:/etc/mysql
      - ./logs/mariadb_logs/db102:/var/log
      - /etc/localtime:/etc/localtime
      - mariadb_ubuntu102:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      ohrmdevnet-ubuntu:
        ipv4_address: 10.10.0.7
    restart: always
    container_name: dev_ubuntu_mariadb_102

volumes:
  mariadb_ubuntu102:

networks:
  ohrmdevnet-ubuntu:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.0.0/16
         gateway: 10.10.0.1
