version: '2'
services:
  web:
    image: rshariffdeen/orangehrm-dev-image
    ports:
      - "8080:80"
    volumes:
      - ./ohrm_dev:/var/www/html
      - ./config/php5/apache2:/etc/php5/apache2
      - ./config/php5/cli:/etc/php5/cli
      - ./config/mysql-client:/etc/mysql
      - ./config/apache2:/etc/apache2
      - ./logs/ubuntu_logs:/var/log
    links:
      - db
      - phpmyadmin
    container_name: dev_web

  db:
    image: mysql:5.5
    expose:
      - "3306"
    volumes:
      - ./config/mysql-server:/etc/mysql
      - ./logs/mysql_logs:/var/log
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    container_name: dev_mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./logs/phpmyadmin_logs:/var/log
    links:
      - db
    ports:
      - "9090:80"
    environment:
      PMA_HOST: db
    container_name: dev_phpmyadmin