version: '2'
services:
  web:
    image: rshariffdeen/orangehrm-dev-image
    ports:
      - "8080:80"
    volumes:
      - ./ohrm_dev:/var/www/html
      - ./config/php5/apache2:/etc/php5/apache2
      - ./config/php5/cli:/etc/php5/cli
    depends_on:
      - mysql
      - phpmyadmin
    container_name: dev_web
    command:
      - /usr/sbin/apache2ctl -D FOREGROUND

  mysql:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    container_name: dev_mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "9090:80"
    environment:
      PMA_HOST: mysql
    container_name: dev_phpmyadmin