version: '2.2'
services:
  nginx:
    image: nginx:1.14
    ports:
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/virtual-servers:/etc/nginx/conf.d/virtual-servers
      - ./config/nginx/cert:/etc/nginx/cert
      - ./config/nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx_logs/web56:/var/log/nginx/web56
      - ./logs/nginx_logs/web70:/var/log/nginx/web70
      - ./logs/nginx_logs/web71:/var/log/nginx/web71
      - ./logs/nginx_logs/web72:/var/log/nginx/web72
      - ./logs/nginx_logs/webubuntu71:/var/log/nginx/webubuntu71
      - ./logs/nginx_logs/phpmyadmin:/var/log/nginx/phpmyadmin
      - ./logs/nginx_logs/rabbitmq:/var/log/nginx/rabbitmq
      - /etc/localtime:/etc/localtime
    privileged: true
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.2.1
    restart: always
    container_name: dev_nginx

  web56:
    image: orangehrm/orangehrm-environment-images:dev-5.6-centos-orange
    volumes:
      - ./html:/var/www/html
      - ./config/web56/php/custom_php.ini:/etc/php.d/custom_php.ini
      - ./config/web56/mysql-client:/etc/mysql
      - ./config/web56/apache2/sites-available:/etc/httpd/sites-available
      - ./config/web56/apache2/sites-enabled:/etc/httpd/sites-enabled
      - ./config/web56/apache2/cert:/etc/httpd/cert
      - ./config/web56/apache2/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
      - ./logs/apache_logs/web56:/var/log/httpd
      - /etc/localtime:/etc/localtime
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.56
    restart: always
    container_name: dev_web_56

  web71:
    image: orangehrm/orangehrm-environment-images:dev-7.1-centos-orange
    volumes:
      - ./html:/var/www/html
      - ./config/web71/php/custom_php.ini:/etc/php.d/custom_php.ini
      - ./config/web71/mysql-client:/etc/mysql
      - ./config/web71/apache2/sites-available:/etc/httpd/sites-available
      - ./config/web71/apache2/sites-enabled:/etc/httpd/sites-enabled
      - ./config/web56/apache2/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
      - ./config/web71/apache2/cert:/etc/httpd/cert
      - ./logs/apache_logs/web71:/var/log/httpd
      - /etc/localtime:/etc/localtime
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    sysctls:
      - kernel.shmmax=67371264
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.71
    restart: always
    container_name: dev_web_71

  web72:
    image: orangehrm/orangehrm-environment-images:dev-7.2-centos-orange
    volumes:
    - ./html:/var/www/html
    - ./config/web72/php/custom_php.ini:/etc/php.d/custom_php.ini
    - ./config/web72/mysql-client:/etc/mysql
    - ./config/web72/apache2/sites-available:/etc/httpd/sites-available
    - ./config/web72/apache2/sites-enabled:/etc/httpd/sites-enabled
    - ./config/web72/apache2/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
    - ./config/web72/apache2/cert:/etc/httpd/cert
    - ./logs/apache_logs/web72:/var/log/httpd
    - /etc/localtime:/etc/localtime
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    sysctls:
    - kernel.shmmax=67371264
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.72
    restart: always
    container_name: dev_web_72
  
  web73:
    image: orangehrm/orangehrm-environment-images:dev-7.3-centos-orange
    volumes:
    - ./html:/var/www/html
    - ./config/web73/php/custom_php.ini:/etc/php.d/custom_php.ini
    - ./config/web73/mysql-client:/etc/mysql
    - ./config/web73/apache2/sites-available:/etc/httpd/sites-available
    - ./config/web73/apache2/sites-enabled:/etc/httpd/sites-enabled
    - ./config/web73/apache2/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
    - ./config/web73/apache2/cert:/etc/httpd/cert
    - ./logs/apache_logs/web73:/var/log/httpd
    - /etc/localtime:/etc/localtime
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    sysctls:
    - kernel.shmmax=67371264
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.73
    restart: always
    container_name: dev_web_73

  web74:
    image: orangehrm/orangehrm-environment-images:dev-7.4-centos-orange
    volumes:
    - ./html:/var/www/html
    - ./config/web74/php/custom_php.ini:/etc/php.d/custom_php.ini
    - ./config/web74/mysql-client:/etc/mysql
    - ./config/web74/apache2/sites-available:/etc/httpd/sites-available
    - ./config/web74/apache2/sites-enabled:/etc/httpd/sites-enabled
    - ./config/web74/apache2/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
    - ./config/web74/apache2/cert:/etc/httpd/cert
    - ./logs/apache_logs/web74:/var/log/httpd
    - /etc/localtime:/etc/localtime
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    sysctls:
    - kernel.shmmax=67371264
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.74
    restart: always
    container_name: dev_web_74

  web_74_rh:
    image: orangehrm/orangehrm-environment-images:dev-7.4-rhel-a1
    volumes:
    - ./html:/var/www/html
    - ./config/web74rh/php/custom_php.ini:/etc/php.d/custom_php.ini
    - ./config/web74rh/mysql-client:/etc/mysql
    - ./config/web74rh/apache2/sites-available:/etc/httpd/sites-available
    - ./config/web74rh/apache2/sites-enabled:/etc/httpd/sites-enabled
    - ./config/web74rh/apache2/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
    - ./config/web74rh/apache2/cert:/etc/httpd/cert
    - ./logs/apache_logs/web74rh:/var/log/httpd
    - /etc/localtime:/etc/localtime
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    sysctls:
    - kernel.shmmax=67371264
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.174
    restart: always
    container_name: dev_web_74_rh  

  db57:
    image: orangehrm/orangehrm-db-images:mysql-5.7
    expose:
    - "3306"
    volumes:
    - ./logs/mysql_logs/db55:/var/log
    - /etc/localtime:/etc/localtime
    - mysql57:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.1.57
    restart: always
    container_name: dev_mysql_57

  db102:
    image: orangehrm/orangehrm-db-images:mariadb-10.2
    expose:
      - "3306"
    volumes:
      - ./logs/mysql_logs/db102:/var/log
      - /etc/localtime:/etc/localtime
      - mariadb102:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.1.102
    restart: always
    container_name: dev_mariadb_102

  db105:
    image: orangehrm/orangehrm-db-images:mariadb-10.5.13-redhat-8.4
    expose:
    - "3306"
    volumes:
    - ./logs/mysql_logs/db105:/var/log
    - /etc/localtime:/etc/localtime
    - mariadb105:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.1.105
    restart: always
    container_name: dev_mariadb_105

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
    - /etc/localtime:/etc/localtime
    environment:
      PMA_HOSTS: db55,db102,db105
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.2.2
    restart: always
    container_name: dev_phpmyadmin

  rabbitmq:
    image: orangehrm/orangehrm-rabbitmq:3.8.4-management
    container_name: dev_rabbitmq
    volumes:
    - ./config/rabbitmq/certs:/cert_rabbitmq/
    environment:
      RABBITMQ_SSL_CERTFILE: /cert_rabbitmq/cert.pem
      RABBITMQ_SSL_KEYFILE: /cert_rabbitmq/key.pem
      RABBITMQ_SSL_CACERTFILE: /cert_rabbitmq/cacert.pem
      RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: 'false'
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbit ssl_listeners [{"::",5671}] -rabbit ssl_options [{certfile,"/cert_rabbitmq/cert.pem"},{keyfile,"/cert_rabbitmq/key.pem"},{cacertfile,"/cert_rabbitmq/cacert.pem"},{verify,verify_peer},{depth,3},{fail_if_no_peer_cert,false}] -rabbit tcp_listeners [{"::",5672}]'
    ports:
      - "15671:15671"
      - "5672:5672"
      - "5671:5671"
    restart: always
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.2.3

  rabbitmq_rhel:
    image: orangehrm/orangehrm-rabbitmq:rabbitmq-3.9.8-redhat-8.4
    container_name: dev_rabbitmq_rhel
    ports:
      - "18671:15671"
      - "8671:5671"
    volumes:
    - ./config/rabbitmq_398_rhel/certs:/cert_rabbitmq/
    - ./config/rabbitmq_398_rhel/conf:/etc/rabbitmq
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.2.6
    restart: always
    hostname: dev-rabbitmq-rhel

volumes:
  mysql57:
  mariadb102:
  mariadb105:

networks:
  ohrmdevnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
