version: '2'
services:
  web:
    image: orangehrm/orangehrm-environment-images:dev-5.5
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./ohrm_dev:/var/www/html
      - ./config/php5/apache2/php.ini:/etc/php5/apache2/php.ini
      - ./config/php5/cli/php.ini:/etc/php5/cli/php.ini
      - ./config/mysql-client:/etc/mysql
      - ./config/apache2/sites-available:/etc/apache2/sites-available
      - ./config/apache2/cert:/etc/apache2/cert
      - ./logs/ubuntu_logs:/var/log/apache2
      - /etc/localtime:/etc/localtime
      - ./config/xhgui/config.php:/usr/local/src/xhgui/config/config.php
    links:
      - db
      - phpmyadmin
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.2
    restart: always
    container_name: dev_web

  db:
    image: mysql:5.5
    expose:
      - "3306"
    volumes:
      - ./config/mysql-server:/etc/mysql
      - ./logs/mysql_logs:/var/log
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.3
    restart: always
    container_name: dev_mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - /etc/localtime:/etc/localtime
    links:
      - db
    ports:
      - "9090:80"
    environment:
      PMA_HOST: db
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.4
    restart: always
    container_name: dev_phpmyadmin
networks:
  ohrmdevnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
