version: '2.2'
services:
  db57:
    image: orangehrm/orangehrm-db-images:mysql-5.7
    expose:
    - "3306"
    volumes:
    - ./logs/mysql_logs/db55:/var/log
    - /etc/localtime:/etc/localtime
    - mysql57:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.1.57
    restart: always
    container_name: dev_mysql_57

volumes:
  mysql57: