version: '2.2'
services:
  web74:
    image: orangehrm/orangehrm-environment-images:uat-5.4-debian
    volumes:
    - ./html:/var/www/html
    - ./custom-compose/config/web54/apache2/sites-enabled:/etc/apache2/sites-enabled
    - ./custom-compose/config/web54/apache2/cert:/etc/apache2/cert
    - ./custom-compose/config/web54/apache2/conf.d/apache2.conf:/etc/apache2/apache2.conf
    - ./custom-compose/logs/apache_logs/web54:/var/log/apache2
    - /etc/localtime:/etc/localtime
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    sysctls:
    - kernel.shmmax=67371264
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.54
    restart: always
    container_name: dev_web_54
