version: '2.2'
services:
  web71:
    image: orangehrm/orangehrm-environment-images:dev-7.1-centos-orange
    volumes:
      - ./html:/var/www/html
      - ./config/web71/php/custom_php.ini:/etc/php.d/custom_php.ini
      - ./config/web71/mysql-client:/etc/mysql
      - ./config/web71/apache2/sites-available:/etc/httpd/sites-available
      - ./config/web71/apache2/sites-enabled:/etc/httpd/sites-enabled
      - ./config/web56/apache2/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
      - ./config/web71/apache2/cert:/etc/httpd/cert
      - ./logs/apache_logs/web71:/var/log/httpd
      - /etc/localtime:/etc/localtime
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    sysctls:
      - kernel.shmmax=67371264
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.0.71
    restart: always
    container_name: dev_web_71